services:
  # Base de datos MongoDB
  mongo:
    image: mongo:latest
    container_name: access_pass_mongo_dev
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: access_pass_db
    volumes:
      - mongo_data_dev:/data/db

  # Broker MQTT (Mosquitto)
  mqtt:
    image: eclipse-mosquitto:latest
    container_name: access_pass_mqtt_dev
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf

volumes:
  mongo_data_dev: